# ----------- CONFIGURABLE START -----------
title:            "LiberXue|FullStack|独立开发者|jekyll blog|GitHub blog"
description:      "Full Stack独立开发者|欢迎来到 LiberXue「角落」侃侃理想、谈谈人生、敲敲代码。"
url:              https://libertheme.github.io # 域名
signoff:          "LiberXue" # Your name
facebook_appid:   #liberxue
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         Trang chủ
    url:          https://libertheme.github.io/index.html #Link
    external:     false
  - name:         Sách
    url:          https://libertheme.github.io/book
    external:     false
  - name:         Du lịch
    url:          https://libertheme.github.io/road
    external:     false
  - name:         Lưu trữ
    url:          https://libertheme.github.io/archives
    external:     false
  - name:         Nhãn
    url:          https://libertheme.github.io/tags
    external:     false
  - name:         Giới thiệu
    url:          https://libertheme.github.io/about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
