# ----------- CONFIGURABLE START -----------
title:            "Book Store"
description:      "Full Stack- OverFlow"
url:              https://libertheme.github.io # Tên miền
signoff:          "Elliot Alderson" # Your name
facebook_appid:   #liberxue
google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         Trang chủ
    url:          https://libertheme.github.io #Link
    external:     false
  - name:         Sách
    url:          https://libertheme.github.io/book
    external:     false
  - name:         Du lịch
    url:          https://libertheme.github.io/road
    external:     false
  - name:         Lưu trữ
    url:          https://libertheme.github.io/archives
    external:     false
  - name:         Nhãn
    url:          https://libertheme.github.io/tags
    external:     false
  - name:         Giới thiệu
    url:          https://libertheme.github.io/about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
